### ISSUE TITLE
How do we specify file paths for EEG files for PathFinder?

### ISSUE THREAD

**Issue by mivade** [pennmem/cmlreaders#34]
EEG files have names similar to `R1387E_FR1_0_25Jan18_1826.h5` for Ramulator HDF5 files or `R1337E_FR1_0_08Sep17_2045.030` for "split" EEG files. When using the `PathFinder`, how can we account for these timestamped filenames?

One idea is to only point to the directory and let `EEGReader` handle it from there. Other ideas, @zduey?

**Comment by zduey** [comment]
First thing that comes to mind for me is to use something like {subject}_{experiment}_{session}_*. That would work for the .h5 files, but split EEG is weird because there are multiple and PathFinder is set up with the assumption of only finding a single file. 

Another option is to have two EEG file-paths defined: "eeg" and "split_eeg". The path for "eeg" would look like the example above, and "split_eeg" would be more like {subject}_{experiment}_{session}_*.{channel} and it would be up to the EEGReader to supply the channel number. This goes a bit against PathFinder because it is supposed to allow the user to remain agnostic to how the data are stored.

My tentative preference is to have "eeg" and "split_eeg" defined as separate data types. If a user attempts to use "eeg" and PathFinder determines that what they are requesting are split EEG, then it should raise an informative error and tell the user to use the "split_eeg" data type instead and provide a channel number.

**Comment by mivade** [comment]
I don't like the idea of separating them because then we're back to the situation of users having to know about the data before they can read the data.

Maybe `PathFinder` should just return the path to `sources.json` rather than the EEG data itself since that describes the EEG data?

**Comment by mivade** [comment]
What's actually looking like the easiest way to do this is to just ignore looking for a file at all when loading EEG data with `CMLReader`. Internally, the generic `EEGReader` loads `sources.json` and figures out what to do based on what it finds there.

**Comment by zduey** [comment]
What you said about CMLReader makes sense to me. I still think there should be a way to find EEG files with PathFinder. In that case, I'd prefer returning the folder over returning `sources.json` since it would be confusing to me as a user to ask for EEG and get back some metadata file.  We can define only the "eeg" data type and return the full path to the combined file when that is available, and return the folder location in the case of split EEG.
